# Generated by Django 4.1 on 2022-09-11 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_account_age_alter_account_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='account',
            name='weight',
            field=models.IntegerField(),
        ),
    ]
