# Generated by Django 4.1 on 2022-09-13 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_account_age_alter_account_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='height',
            field=models.CharField(default="5'11", max_length=3),
            preserve_default=False,
        ),
    ]
