# Generated by Django 4.1 on 2022-09-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_account_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='height',
            field=models.CharField(max_length=5),
        ),
    ]
