# Generated by Django 4.1 on 2022-09-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_account_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='height_in_inches',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='height',
            field=models.CharField(max_length=3),
        ),
    ]
